import Head from 'next/head'
import clsx from 'clsx'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1 className={clsx(
          'italic', 
          'text-vet-blue', 
          'text-3xl'
        )}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h1 className={clsx(
          'italic', 
          'text-vet-blue-600', 
          'text-3xl'
        )}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h1 className={clsx(
          'italic', 
          'text-vet-blue-700', 
          'text-3xl'
        )}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
    </>
  )
}
